<?php

namespace Tests\FakeAPIData;

use Carbon\Carbon;

trait WeatherData
{
    /**
     * Get the next 7-day forecast.
     *
     * @return array
     */
    public function FackForecastData(): array
    {
        $date = Carbon::now('UTC');

        return [
            'data' => [[
                'moonrise_ts' => 1576505868,
                'wind_cdir' => 'SE',
                'rh' => 17,
                'pres' => 975.33,
                'high_temp' => 41.3,
                'sunset_ts' => 1576576911,
                'ozone' => 281.046,
                'moon_phase' => 0.631084,
                'wind_gust_spd' => 9.00117,
                'snow_depth' => 0,
                'clouds' => 74,
                'ts' => 1576503060,
                'sunrise_ts' => 1576524620,
                'app_min_temp' => 17.9,
                'wind_spd' => 2.62832,
                'pop' => 0,
                'wind_cdir_full' => 'southeast',
                'slp' => 1013.92,
                'valid_date' => '2019-12-17',
                'app_max_temp' => 37.8,
                'vis' => 24.135,
                'dewpt' => 0.1,
                'snow' => 0,
                'uv' => 4.73689,
                'weather' => [
                    'icon' => 'c04d',
                    'code' => 804,
                    'description' => 'Overcast clouds',
                ],
                'wind_dir' => 130,
                'max_dhi' => null,
                'clouds_hi' => 73,
                'precip' => 0,
                'low_temp' => 23.6,
                'max_temp' => 41.6,
                'moonset_ts' => 1576545971,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 29.4,
                'min_temp' => 19.1,
                'clouds_mid' => 6,
                'clouds_low' => 0,
            ],
            [
                'moonrise_ts' => 1576594473,
                'wind_cdir' => 'S',
                'rh' => 17,
                'pres' => 973.369,
                'high_temp' => 41.1,
                'sunset_ts' => 1576663346,
                'ozone' => 274.123,
                'moon_phase' => 0.512546,
                'wind_gust_spd' => 14.2065,
                'snow_depth' => 0,
                'clouds' => 19,
                'ts' => 1576589460,
                'sunrise_ts' => 1576611041,
                'app_min_temp' => 22.8,
                'wind_spd' => 3.27358,
                'pop' => 0,
                'wind_cdir_full' => 'south',
                'slp' => 1011.33,
                'valid_date' => '2019-12-18',
                'app_max_temp' => 37.7,
                'vis' => 24.1349,
                'dewpt' => 2.3,
                'snow' => 0,
                'uv' => 11.5943,
                'weather' => [
                    'icon' => 'c02d',
                    'code' => 801,
                    'description' => 'Few clouds',
                ],
                'wind_dir' => 170,
                'max_dhi' => null,
                'clouds_hi' => 6,
                'precip' => 0,
                'low_temp' => 24.1,
                'max_temp' => 41.1,
                'moonset_ts' => 1576636412,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 32.6,
                'min_temp' => 23.4,
                'clouds_mid' => 13,
                'clouds_low' => 0,
            ],
            [
                'moonrise_ts' => 1576682925,
                'wind_cdir' => 'S',
                'rh' => 15,
                'pres' => 971.251,
                'high_temp' => 42.8,
                'sunset_ts' => 1576749780,
                'ozone' => 269.548,
                'moon_phase' => 0.393379,
                'wind_gust_spd' => 8.40548,
                'snow_depth' => 0,
                'clouds' => 21,
                'ts' => 1576675860,
                'sunrise_ts' => 1576697464,
                'app_min_temp' => 23.9,
                'wind_spd' => 2.68837,
                'pop' => 0,
                'wind_cdir_full' => 'south',
                'slp' => 1009.08,
                'valid_date' => '2019-12-19',
                'app_max_temp' => 38.8,
                'vis' => 24.135,
                'dewpt' => 1.4,
                'snow' => 0,
                'uv' => 11.6117,
                'weather' => [
                    'icon' => 'c02d',
                    'code' => 802,
                    'description' => 'Scattered clouds',
                ],
                'wind_dir' => 181,
                'max_dhi' => null,
                'clouds_hi' => 1,
                'precip' => 0,
                'low_temp' => 28.5,
                'max_temp' => 42.9,
                'moonset_ts' => 1576726812,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 34.1,
                'min_temp' => 23.8,
                'clouds_mid' => 20,
                'clouds_low' => 0,
            ],
            [
                'moonrise_ts' => 1576771315,
                'wind_cdir' => 'S',
                'rh' => 27,
                'pres' => 969.231,
                'high_temp' => 42.1,
                'sunset_ts' => 1576836212,
                'ozone' => 265.502,
                'moon_phase' => 0.280646,
                'wind_gust_spd' => 13.6225,
                'snow_depth' => 0,
                'clouds' => 53,
                'ts' => 1576762260,
                'sunrise_ts' => 1576783889,
                'app_min_temp' => 18.2,
                'wind_spd' => 4.4092,
                'pop' => 20,
                'wind_cdir_full' => 'south',
                'slp' => 1007.06,
                'valid_date' => '2019-12-20',
                'app_max_temp' => 40.1,
                'vis' => 24.135,
                'dewpt' => 8.2,
                'snow' => 0,
                'uv' => 8.82168,
                'weather' => [
                    'icon' => 'c03d',
                    'code' => 803,
                    'description' => 'Broken clouds',
                ],
                'wind_dir' => 189,
                'max_dhi' => null,
                'clouds_hi' => 32,
                'precip' => 0.6875,
                'low_temp' => 14,
                'max_temp' => 42.1,
                'moonset_ts' => 1576817197,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 32.1,
                'min_temp' => 16.7,
                'clouds_mid' => 34,
                'clouds_low' => 0,
            ],
            [
                'moonrise_ts' => 1576859731,
                'wind_cdir' => 'SSE',
                'rh' => 66,
                'pres' => 975.937,
                'high_temp' => 22.6,
                'sunset_ts' => 1576922642,
                'ozone' => 265.03,
                'moon_phase' => 0.180903,
                'wind_gust_spd' => 9.00081,
                'snow_depth' => 0,
                'clouds' => 97,
                'ts' => 1576848660,
                'sunrise_ts' => 1576870315,
                'app_min_temp' => 12.1,
                'wind_spd' => 3.46437,
                'pop' => 20,
                'wind_cdir_full' => 'south-southeast',
                'slp' => 1016.07,
                'valid_date' => '2019-12-21',
                'app_max_temp' => 21.5,
                'vis' => 24.1349,
                'dewpt' => 9.5,
                'snow' => 0,
                'uv' => 4.86423,
                'weather' => [
                    'icon' => 'c04d',
                    'code' => 804,
                    'description' => 'Overcast clouds',
                ],
                'wind_dir' => 150,
                'max_dhi' => null,
                'clouds_hi' => 87,
                'precip' => 0.1875,
                'low_temp' => 11,
                'max_temp' => 22.3,
                'moonset_ts' => 1576907590,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 16.5,
                'min_temp' => 11.6,
                'clouds_mid' => 69,
                'clouds_low' => 23,
            ],
            [
                'moonrise_ts' => 1576946131,
                'wind_cdir' => 'ESE',
                'rh' => 51,
                'pres' => 977.056,
                'high_temp' => 29.4,
                'sunset_ts' => 1577009071,
                'ozone' => 269.378,
                'moon_phase' => 0.0997429,
                'wind_gust_spd' => 10.5,
                'snow_depth' => 0,
                'clouds' => 99,
                'ts' => 1576935060,
                'sunrise_ts' => 1576956744,
                'app_min_temp' => 11,
                'wind_spd' => 3.32539,
                'pop' => 20,
                'wind_cdir_full' => 'east-southeast',
                'slp' => 1017.39,
                'valid_date' => '2019-12-22',
                'app_max_temp' => 21.8,
                'vis' => 23.7101,
                'dewpt' => 5.2,
                'snow' => 0,
                'uv' => 3.60348,
                'weather' => [
                    'icon' => 'c04d',
                    'code' => 804,
                    'description' => 'Overcast clouds',
                ],
                'wind_dir' => 115,
                'max_dhi' => null,
                'clouds_hi' => 93,
                'precip' => 0.1875,
                'low_temp' => 16.3,
                'max_temp' => 26.6,
                'moonset_ts' => 1576997995,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 16.2,
                'min_temp' => 10.4,
                'clouds_mid' => 98,
                'clouds_low' => 15,
            ],
            [
                'moonrise_ts' => 1576946131,
                'wind_cdir' => 'ESE',
                'rh' => 51,
                'pres' => 977.056,
                'high_temp' => 29.4,
                'sunset_ts' => 1577009071,
                'ozone' => 269.378,
                'moon_phase' => 0.0997429,
                'wind_gust_spd' => 10.5,
                'snow_depth' => 0,
                'clouds' => 99,
                'ts' => 1576935060,
                'sunrise_ts' => 1576956744,
                'app_min_temp' => 11,
                'wind_spd' => 3.32539,
                'pop' => 20,
                'wind_cdir_full' => 'east-southeast',
                'slp' => 1017.39,
                'valid_date' => '2019-12-22',
                'app_max_temp' => 21.8,
                'vis' => 23.7101,
                'dewpt' => 5.2,
                'snow' => 0,
                'uv' => 3.60348,
                'weather' => [
                    'icon' => 'c04d',
                    'code' => 804,
                    'description' => 'Overcast clouds',
                ],
                'wind_dir' => 115,
                'max_dhi' => null,
                'clouds_hi' => 93,
                'precip' => 0.1875,
                'low_temp' => 16.3,
                'max_temp' => 26.6,
                'moonset_ts' => 1576997995,
                'datetime' => $date->add(1, 'day')->format('Y-m-d'),
                'temp' => 16.2,
                'min_temp' => 10.4,
                'clouds_mid' => 98,
                'clouds_low' => 15,
            ],
        ],
            'city_name' => 'THIS_IS_TEST_CITY',
            'lon' => '138.59863',
            'timezone' => 'Australia/Adelaide',
            'lat' => '-34.92866',
            'country_code' => 'AU',
            'state_code' => '05',
        ];
    }
}
